<a href="https://colab.research.google.com/github/ChuanHung/Pytroch-Tutoral-Youtube/blob/main/Intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


List - 陣列

In [ ]:
my_list = [1,2,3,4,5],[6,7,8,9,10]
my_list

[1, 2, 3, 4, 5]

Numpy Arrays - 矩陣陣列

In [ ]:
np1 = np.random.rand(4,5)
np1

array([[0.83628033, 0.45852682, 0.08898459, 0.23828567, 0.42309585],
       [0.39809878, 0.73162522, 0.60692074, 0.73571356, 0.24646856],
       [0.67002739, 0.32283065, 0.24616404, 0.49258765, 0.60757102],
       [0.95236411, 0.54309956, 0.41262756, 0.69896162, 0.39977275]])

Tensor - 張量

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8065,  0.6784, -0.2756,  0.2052],
        [ 0.3770, -0.1745, -0.6690, -0.3657],
        [ 0.2861, -0.7234,  1.0207, -0.6864]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor out numpy array - 建立張量超過陣列
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8363, 0.4585, 0.0890, 0.2383, 0.4231],
        [0.3981, 0.7316, 0.6069, 0.7357, 0.2465],
        [0.6700, 0.3228, 0.2462, 0.4926, 0.6076],
        [0.9524, 0.5431, 0.4126, 0.6990, 0.3998]], dtype=torch.float64)